// Auto-generated by Vercel build from PLANT_API_BASE.
// To change in prod: Vercel -> Settings -> Environment Variables.
window.__PLANT_API_URL__ = "https://plant-ai-project-production.up.railway.app";
