// PlantVision Dynamic API Endpoint Configuration
// In production, this file is regenerated by Vercel's buildCommand (see
// frontend/vercel.json) from the PLANT_API_BASE env var. The committed
// default below points at the live Railway backend so the static frontend
// also works when served outside of Vercel (e.g. opened directly or via
// frontend/mobile-app/server.js). Devs can still override at runtime via:
//   ?api=http://localhost:8000   (URL query string)
//   localStorage.setItem('pv-api-base','http://localhost:8000')
window.__PLANT_API_URL__ = "https://plant-ai-project-production.up.railway.app";
