// Vercel build helper for PlantVision frontend.
//
// Generates mobile-app/env.js from the PLANT_API_BASE environment variable.
// Falls back to the live Railway backend if PLANT_API_BASE is unset so a
// clean clone still talks to the real API out of the box.
//
// To change the API URL in production, set PLANT_API_BASE in:
//   Vercel -> Project -> Settings -> Environment Variables
//
// This file is invoked from vercel.json via `node build-env.js`.

const fs = require("fs");
const path = require("path");

const DEFAULT_API_BASE = "https://plant-ai-project-production.up.railway.app";

const raw = (process.env.PLANT_API_BASE || DEFAULT_API_BASE).trim();
const apiBase = raw.replace(/\/$/, "");

const outDir = path.join(__dirname, "mobile-app");
const outFile = path.join(outDir, "env.js");

const contents =
  "// Auto-generated by Vercel build from PLANT_API_BASE.\n" +
  "// To change in prod: Vercel -> Settings -> Environment Variables.\n" +
  "window.__PLANT_API_URL__ = " + JSON.stringify(apiBase) + ";\n";

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, contents);

console.log(
  "[vercel build] wrote " +
    path.relative(__dirname, outFile) +
    " with PLANT_API_BASE=" +
    JSON.stringify(apiBase)
);
